"""
Django settings for Viserpel project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
#encoding:utf-8

import os
import time

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP_DIR = os.path.join(BASE_DIR, 'vi_peli')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-#+r=!hjjln#=%w0pdh4)-xn!temffed8v&hpr=c3#9h(4hrp%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'vi_peli',
    'djcelery',
    'djkombu',
    'pure_pagination',
    'bootstrap3',
    'django_popup_view_field',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Viserpel.urls'
MEDIA_ROOT = os.path.join(APP_DIR,'static\Imagenes')
PATH_FOTOS_PELIS = 'pelis'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Viserpel.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'viserpel.sqlite3'),
    }
}
DEFAULT_INDEX_TABLESPACE = ''
# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

JSON_URL = '/json/'
JSON_ROOT =  os.path.join (APP_DIR, 'json')

# Logging ejemplo

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'normal': {
            'format': "%(asctime)s : %(levelname)s : %(message)s",
        },
        'simple': {'format': "%(message)s",}
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(APP_DIR, 'log', 'vi_peli'+str(time.strftime("%Y%m%d"))+'.log'),
            'formatter': 'normal'
        },
        'consola': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
    },
    'loggers': {
        'vi_peli': {
            'handlers': ['file', 'consola'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
#Si queremos usar la base de datos como backend:
#CELERY_RESULT_BACKEND='djcelery.backends.database:DatabaseBackend'

#Si queremos usar la cache como backend:
#CELERY_RESULT_BACKEND='djcelery.backends.cache:CacheBackend'

# ----------------------------------------------------------------------------
# CELERY
# ----------------------------------------------------------------------------
"""
CELERY_BROKER_URL = 'amqp://guest:{}@localhost:5672//'
CELERY_TASK_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["application/json"]

CELERY_TASK_DEFAULT_QUEUE = "Viserpel_celery"
CELERY_TASK_DEFAULT_EXCHANGE = "Viserpel_celery"
CELERY_TASK_DEFAULT_ROUTING_KEY = "Viserpel_celery"
CELERY_TIMEZONE = 'Europe/Madrid'

CELERY_DEFAULT_EXCHANGE = Exchange(CELERY_TASK_DEFAULT_EXCHANGE, type='direct')

task_queues = (
    Queue(CELERY_TASK_DEFAULT_QUEUE, CELERY_DEFAULT_EXCHANGE, routing_key=CELERY_TASK_DEFAULT_ROUTING_KEY),
)
"""

#--------------------- PAGINACION -----------------------
PAGINATION_SETTINGS = {
    'PAGE_RANGE_DISPLAYED': 30,
    'MARGIN_PAGES_DISPLAYED': 2,

    'SHOW_FIRST_PAGE_WHEN_INVALID': True,
}