# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista_Pelis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('enlace', models.TextField()),
                ('fecha_busqueda', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('anyo', models.IntegerField(null=True)),
                ('torrent', models.TextField()),
                ('calidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_imbd', models.IntegerField(null=True)),
                ('titulo', models.CharField(max_length=500)),
                ('titulo_orig', models.CharField(max_length=500)),
                ('generos', models.TextField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('imagen', models.TextField(null=True)),
                ('director', models.CharField(max_length=500, null=True)),
                ('actores', models.TextField(null=True)),
                ('sinopsis', models.TextField(null=True)),
            ],
        ),
    ]
