# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vi_peli', '0005_auto_20180101_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista_pelis',
            name='imagen',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lista_pelis',
            name='proveedor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lista_pelis',
            name='calidad',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
