# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vi_peli', '0008_auto_20180102_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_pelis',
            name='anyo',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
