# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vi_peli', '0011_auto_20180105_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista_pelis',
            name='idimbd',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lista_pelis',
            name='tamanio',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='lista_pelis',
            name='titulo_orig',
            field=models.TextField(default=models.TextField(db_tablespace='indexes')),
        ),
        migrations.AlterField(
            model_name='lista_pelis',
            name='fecha_publicacion',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
