# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vi_peli', '0012_auto_20180110_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista_pelis',
            name='idimbd',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='id_imbd',
        ),
        migrations.AddField(
            model_name='lista_pelis',
            name='idFicha',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='idFicha',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
