# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vi_peli', '0013_auto_20180115_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_pelis',
            name='fecha_busqueda',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
