# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-13 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vi_peli', '0015_auto_20180207_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_pelis',
            name='titulo_orig',
            field=models.TextField(default=models.TextField(db_tablespace='indexes'), null=True),
        ),
    ]
