# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vi_peli', '0016_auto_20180213_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(null=True)),
                ('audio', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='mispelis',
            name='tipo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='f_alta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mispelis',
            name='idPeli',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mipeli', to='vi_peli.Pelicula'),
        ),
        migrations.AlterField(
            model_name='mispelis',
            name='titulo_orig',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
