# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vi_peli', '0017_auto_20180218_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='calidades',
            name='calidad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='calidades',
            name='otros_nombres',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='calidades',
            name='audio',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
