# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vi_peli', '0020_auto_20180301_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_pelis',
            name='idFicha',
            field=models.IntegerField(null=True),
        ),
    ]
