# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vi_peli', '0021_auto_20180307_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_pelis',
            name='idFicha',
            field=models.ForeignKey(db_column='idFicha', null=True, on_delete=django.db.models.deletion.CASCADE, to='vi_peli.Pelicula'),
        ),
    ]
