# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vi_peli', '0022_auto_20180307_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calidades',
            name='audio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='calidades',
            name='calidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='calidades',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calidades',
            name='otros_nombres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generos',
            name='desc_generos',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lista_pelis',
            name='anyo',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='lista_pelis',
            name='calidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lista_pelis',
            name='idFicha',
            field=models.ForeignKey(blank=True, db_column='idFicha', null=True, on_delete=django.db.models.deletion.CASCADE, to='vi_peli.Pelicula'),
        ),
        migrations.AlterField(
            model_name='lista_pelis',
            name='imagen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lista_pelis',
            name='proveedor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lista_pelis',
            name='sinopsis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lista_pelis',
            name='tamanio',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lista_pelis',
            name='titulo_ben',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lista_pelis',
            name='titulo_bes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lista_pelis',
            name='titulo_orig',
            field=models.TextField(blank=True, default=models.TextField(db_tablespace='indexes'), null=True),
        ),
        migrations.AlterField(
            model_name='mispelis',
            name='calidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mispelis',
            name='idPeli',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mipeli', to='vi_peli.Pelicula'),
        ),
        migrations.AlterField(
            model_name='mispelis',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mispelis',
            name='titulo_orig',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='actores',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='director',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='escritor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='generos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='idFicha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='sinopsis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='sinopsis_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='titulo_ben',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='titulo_bes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='titulo_orig',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
