# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vi_peli', '0023_auto_20180315_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_pelis',
            name='fecha_publicacion',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
